Merge the speed improvements to the main branch
Humans-of-Julia/GraknClient.jl pull request #122
Opened 2021-10-10 16:30 UTC by FrankUrbach

For more speed all possibilities to use more workers on input and output channels are chosen.

2021-10-10 18:25 UTC, tk3369 submitted a review, later dismissed

2021-10-10 18:25 UTC, tk3369 commented on docs/src/changelog.md
> +03.10.2021
May I suggest ISO date format?

2021-10-10 18:25 UTC, tk3369 commented on docs/src/contributing.md
> +This is the new community driven Julia client.
```suggestion
This is the community-driven Julia client.
```

2021-10-10 18:25 UTC, tk3369 commented on docs/src/contributing.md
> +The roadmap for TypeDBClient.jl (01.10.2021):
Please use ISO date format.

2021-10-10 18:25 UTC, tk3369 commented on docs/src/guide.md
> +In the Julia REPL or in your source code run:
```suggestion
In the Julia REPL or in your source code:
```

2021-10-10 18:25 UTC, tk3369 commented on docs/src/guide.md
> +    # Creation of a database
```suggestion
    # Create a database
```

2021-10-10 18:25 UTC, tk3369 commented on docs/src/guide.md
> +    # Opening the session
```suggestion
    # Opening a session
```

2021-10-10 18:25 UTC, tk3369 commented on docs/src/guide.md
> +            # Make a insert with a TypeQL string
```suggestion
            # Insert a record using TypeQL
```

2021-10-10 18:25 UTC, tk3369 commented on docs/src/guide.md
> +            # Committing the transaction.
```suggestion
            # Commit the transaction
```

2021-10-10 18:25 UTC, tk3369 commented on docs/src/guide.md
> +    [`delete_database(client::CoreClient, database_name::String)`](@ref)
Just a thought. I have never used the full method signature in a ref before... Have you tested it?

2021-10-10 18:25 UTC, tk3369 commented on docs/src/guide.md
> +* get_has
I'm pretty sure that you need to quote all code include method names or else the underscore would mess up formatting since it's used in markdown.

2021-10-10 18:25 UTC, tk3369 commented on src/common/Label.jl
> +    name::AbstractString
Hmmm... this should be `String` not `AbstractString`. Use concrete types in structs for performance reason. If needed you can parameterize it:
```julia
struct Label{T <: AbstractString}
  name::T
end
```

Same comment for other places that you changed from `String` to `AbstractString`.

2021-10-10 18:25 UTC, tk3369 commented on src/common/exception/TypeDBClientException.jl
> +function TypeDBClientException(message::AbstractString, cause::T) where {T<:Exception}
Just a note. This change is good... Prefer abstract types in method signature.

2021-10-10 18:25 UTC, tk3369 commented on src/concept/type/ThingType.jl
> +    database which is based on this type.
Looks like too much indent here.

2021-10-10 18:25 UTC, tk3369 commented on src/core/CoreSession.jl
> +
What is this used for? I don't see any new code that references this global variable here.

2021-10-10 18:25 UTC, tk3369 commented on src/core/CoreSession.jl
> +    error_break_time::Real
Prefer concrete types

2021-10-10 18:25 UTC, tk3369 commented on src/stream/RequestTransmitter.jl
> +    for _ in 1:3
Why 3? Should this be defined as a constant? I see another reference below.

2021-10-10 18:25 UTC, tk3369 commented on test/behaviour/concept/type/thingtype/ThingTypeSteps.jl
> +    print_role_types::Bool = false)
This looks like a debug flag. Maybe we should choose a consistent name so you can use the same name in any functions that you need the same e.g. `verbose` or `debug` or something like that.

2021-10-10 18:25 UTC, tk3369 commented on test/behaviour/concept/type/thingtype/ThingTypeSteps.jl
> +function _get_players_contain(relation_name::String, role_name::String, context; should_contain::Bool = true)
See suggestion above for using a consistent name.

2021-10-10 18:25 UTC, tk3369 commented on test/behaviour/connection/transaction/TransactionSteps.jl
> +        context[:session] = g.CoreSession(context[:client], "typedb",
Should "typedb" be a constant?

2021-10-10 18:25 UTC, tk3369 commented on test/behaviour/connection/transaction/TransactionSteps.jl
>      end
This code looks the same as the one above for read. Could we factor out to a function?

2021-10-10 18:25 UTC, tk3369 commented on test/runner.jl
> +# const test_features = [
Can we clean up this chunk of commented code?

2021-10-10 18:25 UTC, tk3369 commented on test/runner.jl
>      throw("TestSuite failed. Please proof the results")
```suggestion
    throw("TestSuite failed. Please review the results")
```

2021-10-10 18:25 UTC, tk3369 commented on test/runner.jl
>      @info "Well done!"
```suggestion
    @info "All tests passed. Well done! 😄 "
```

2021-10-10 18:31 UTC, FrankUrbach commented on docs/src/changelog.md
> +03.10.2021
Will be done

2021-10-10 18:32 UTC, FrankUrbach commented on docs/src/contributing.md
> +This is the new community driven Julia client.
Done

2021-10-10 18:33 UTC, FrankUrbach commented on docs/src/contributing.md
> +This is the new community driven Julia client.
done

2021-10-10 18:37 UTC, FrankUrbach commented on src/common/Label.jl
> +    name::AbstractString
This would be more a future question. What we should do if there are other String packages which can be used for String representation. e.g. Scotts Str.jl package?

2021-10-10 18:37 UTC, FrankUrbach commented on src/concept/type/ThingType.jl
> +    database which is based on this type.
You're right. Done

2021-10-10 18:38 UTC, FrankUrbach commented on src/core/CoreSession.jl
> +
Can be deleted. This was the begin of a thougt which never was fully formulated.

2021-10-10 18:43 UTC, FrankUrbach commented on src/core/CoreSession.jl
> +    error_break_time::Real
Done.

2021-10-10 18:45 UTC, FrankUrbach commented on src/stream/RequestTransmitter.jl
> +    for _ in 1:3
In the first attempot this was the best solution for speed by trial and error. You are rigth by demanding this as a const. Done

2021-10-10 18:49 UTC, FrankUrbach commented on test/behaviour/concept/type/thingtype/ThingTypeSteps.jl
> +    print_role_types::Bool = false)
Your are right. Changed.

2021-10-10 18:50 UTC, FrankUrbach commented on test/behaviour/connection/transaction/TransactionSteps.jl
> +        context[:session] = g.CoreSession(context[:client], "typedb",
Yes. Done.

2021-10-10 18:52 UTC, FrankUrbach commented on test/runner.jl
> +# const test_features = [
Yes of course.

2021-10-10 18:53 UTC, FrankUrbach commented on test/runner.jl
>      throw("TestSuite failed. Please proof the results")
Done

2021-10-10 18:59 UTC, FrankUrbach commented on docs/src/guide.md
> +    [`delete_database(client::CoreClient, database_name::String)`](@ref)
Yes. It works.

2021-10-10 18:59 UTC, FrankUrbach commented on docs/src/guide.md
> +* get_has
As I've seen so far it works.

2021-10-10 19:07 UTC, FrankUrbach commented on test/behaviour/connection/transaction/TransactionSteps.jl
>      end
You are right. Done.

2021-10-17 17:24 UTC, ScottPJones requested changes
I've gotten about half way through, but I've got to go take my son David back to college, so I'll be out for a few hours.
There are a lot of very simple changes to be made throughout the code.

2021-10-17 17:24 UTC, ScottPJones commented on docs/src/examples.md
> +Have Fun and feel free to ask questions in our comminity channel on Discord!
Spelling error!
Also, this line is a duplicate of line 15 - just delete it.

2021-10-17 17:24 UTC, ScottPJones commented on docs/src/examples.md
> +Or if you like to watch a Video, showing how to work with the client in a Notebook, you can watch this recording:
These lines are duplicated on lines 11-13 (I think these should be deleted)

2021-10-17 17:24 UTC, ScottPJones commented on docs/src/guide.md
> +# Only for convencience reasons, you can write the full name if you want
Spelling (convenience)

2021-10-17 17:24 UTC, ScottPJones commented on docs/src/guide.md
> +# Create a database called typedb if the database isn't already created by you previously.
grammar - should be `wasn't already created...` or `doesn't already exist on the server`
(somebody else might have created one by that name)

2021-10-17 17:24 UTC, ScottPJones commented on docs/src/guide.md
> +at the end of your work.=#
I think these are easier to read, if you put the closing `=#` on the next line, and indent the lines with text in between

2021-10-17 17:24 UTC, ScottPJones commented on docs/src/guide.md
>  results = g.match(transaction, raw"""match $x sub thing;""")
Can't this just be: `"match \$x sub thing;"`?  Using `raw` and """ seems like overkill, and make it harder to understand.

2021-10-17 17:24 UTC, ScottPJones commented on docs/src/guide.md
> +    [`delete(r::RemoteConcept{C,T}) where {C <:AbstractThingType, T <: AbstractCoreTransaction}`](@ref)
Do all of these really need to be done with where clauses?  Since this is the documentation and you aren't using the typevars, it would be shorter and simpler to just have:
`delete(r::RemoteConcept{<:AbstractThingType, <:AbstractCoreTransaction})`
(same for all of these below)

2021-10-17 17:24 UTC, ScottPJones commented on docs/src/guide.md
> +    [`delete_database(client::CoreClient, database_name::String)`](@ref)
Shouldn't that be AbstractString instead of String? (same in a few places below)
(check that it's AbstractString in the code as well)

2021-10-17 17:24 UTC, ScottPJones commented on src/common/Label.jl
> +    name::AbstractString
I agree, here it should be simply String, these are not places where it matters, just make sure you can construct it with any type of string, and that if not String (could be SubString, which is part of Base Julia), it converts it (which happens automatically for the default constructors)

2021-10-17 17:24 UTC, ScottPJones commented on src/common/exception/ErrorMessage.jl
>      @eval mutable struct $T <: $A
These should be `String`.
Remember, you want as loose (abstract) as possible for method arguments - but as tight as possible (concrete, fully parameterized, or at most a small union type) for struct fields.

2021-10-17 17:24 UTC, ScottPJones commented on src/common/rpc/RequestBuilder.jl
> +    label::Label, role_label::AbstractString, overridden_label::Optional{String})
Possibly `Optional{<:AbstractString}` here

2021-10-17 17:24 UTC, ScottPJones commented on src/common/rpc/RequestBuilder.jl
> +function get_relations_req(iid::AbstractString, role_types::Optional{AbstractVector{Proto._Type}})
That may need to be `Optional{<:AbstractVector{Proto._Type}})`

2021-10-17 17:24 UTC, ScottPJones commented on src/concept/answer/ConceptMap.jl
> +    conjunction::AbstractString
Keep struct fields as `String`

2021-10-17 17:24 UTC, ScottPJones commented on src/concept/thing/Attribute.jl
> +    iid::AbstractString
same as above

2021-10-17 17:24 UTC, ScottPJones commented on src/concept/thing/Entity.jl
> +    iid::AbstractString
String here

2021-10-17 17:24 UTC, ScottPJones commented on src/concept/thing/Relation.jl
> +    iid::AbstractString
String here

2021-10-17 17:24 UTC, ScottPJones commented on src/concept/type/AttributeType.jl
> +    get_owners(r::RemoteConcept{C,T}, only_key = false) where {
Again, for the docstring, you don't need to have C & T - you only want that if they are used by the other arguments, and not just in the body of the function.

2021-10-17 17:24 UTC, ScottPJones commented on src/concept/type/AttributeType.jl
> +    get_regex(r::RemoteConcept{C,T}) where {
Same here

2021-10-17 17:24 UTC, ScottPJones commented on src/concept/type/AttributeType.jl
>  function get_regex(r::RemoteConcept{C,T}) where {
You are not even using C & T, so you don't need the where clause at all, just do like I showed for the documentation.

2021-10-17 17:24 UTC, ScottPJones commented on src/concept/type/AttributeType.jl
> +    set_regex(r::RemoteConcept{C,T}, regex::Optional{AbstractString}) where {
same for both documentation and code, no need for where clause

2021-10-17 17:24 UTC, ScottPJones commented on src/concept/type/ThingType.jl
> +    set_supertype(r::RemoteConcept{C,T},
same here...

2021-10-17 17:24 UTC, ScottPJones commented on src/concept/type/ThingType.jl
> +        return []
Should this return a vector of type Any?
What is the type of the vector that is returned otherwise?

2021-10-17 17:24 UTC, ScottPJones commented on src/core/CoreDatabase.jl
> +    name::AbstractString
change back to String

2021-10-17 20:51 UTC, FrankUrbach commented on docs/src/examples.md
> +Have Fun and feel free to ask questions in our comminity channel on Discord!
Done

2021-10-17 20:53 UTC, FrankUrbach commented on docs/src/guide.md
> +# Create a database called typedb if the database isn't already created by you previously.
Done

2021-10-17 20:54 UTC, FrankUrbach commented on docs/src/guide.md
> +at the end of your work.=#
Done

2021-10-17 20:56 UTC, FrankUrbach commented on docs/src/guide.md
>  results = g.match(transaction, raw"""match $x sub thing;""")
of course. I for myself use raw because its easier to write if you don't use function calls inside the string.

2021-10-17 20:58 UTC, FrankUrbach commented on src/common/Label.jl
> +    name::AbstractString
If two have the same opinion I will change it at the places where it should be.

2021-10-17 20:59 UTC, FrankUrbach commented on src/common/exception/ErrorMessage.jl
>      @eval mutable struct $T <: $A
Done

2021-10-17 21:00 UTC, FrankUrbach commented on src/common/rpc/RequestBuilder.jl
> +    label::Label, role_label::AbstractString, overridden_label::Optional{String})
Done.

2021-10-17 21:03 UTC, FrankUrbach commented on src/common/rpc/RequestBuilder.jl
> +function get_relations_req(iid::AbstractString, role_types::Optional{AbstractVector{Proto._Type}})
Done

2021-10-17 21:04 UTC, FrankUrbach commented on src/concept/answer/ConceptMap.jl
> +    conjunction::AbstractString
Done

2021-10-17 21:04 UTC, FrankUrbach commented on src/concept/thing/Attribute.jl
> +    iid::AbstractString
Done

2021-10-17 21:05 UTC, FrankUrbach commented on src/concept/thing/Relation.jl
> +    iid::AbstractString
Done

2021-10-17 21:07 UTC, FrankUrbach commented on src/concept/type/AttributeType.jl
> +    set_regex(r::RemoteConcept{C,T}, regex::Optional{AbstractString}) where {
Done

2021-10-17 21:09 UTC, FrankUrbach commented on src/core/CoreDatabase.jl
> +    name::AbstractString
Done

2021-10-17 21:11 UTC, FrankUrbach commented on src/core/CoreDatabase.jl
> +    name::AbstractString
Done

2021-10-17 21:12 UTC, FrankUrbach commented on docs/src/guide.md
> +In the Julia REPL or in your source code run:
Done

2021-10-17 21:13 UTC, FrankUrbach commented on docs/src/guide.md
> +# Only for convencience reasons, you can write the full name if you want
Done

2021-10-17 21:18 UTC, FrankUrbach commented on docs/src/guide.md
> +    [`delete(r::RemoteConcept{C,T}) where {C <:AbstractThingType, T <: AbstractCoreTransaction}`](@ref)
There Tom and you have different opionion maybe tasts. Tom solved this with where clauses you use more the direct approach. But you are rigth. Until we use typevars further in the function body it wouldn't be necessary.

2021-10-17 21:23 UTC, FrankUrbach commented on src/concept/type/AttributeType.jl
> +    get_regex(r::RemoteConcept{C,T}) where {
Done

2021-10-17 21:34 UTC, FrankUrbach commented on src/concept/type/ThingType.jl
> +        return []
The type of the vector will be determnined by the instantiate function. So this can't determined at this place.

2021-10-17 23:03 UTC, ScottPJones requested changes

2021-10-17 23:03 UTC, ScottPJones commented on docs/src/guide.md
> +* If you are only interested in working interactivly, you can use the more simplified API. An example for this is:
spelling (interactively)

2021-10-17 23:03 UTC, ScottPJones commented on docs/src/guide.md
> +#= Make a query in the database
Any of these places where you made a series of 1-line comments into a multi-line comment should be changed as above (i.e. make the end clear by putting on a separate line, and indenting the content)

2021-10-17 23:03 UTC, ScottPJones commented on docs/src/guide.md
> +    [`delete_database(client::CoreClient, database_name::String)`](@ref)
This still needs to be fixed (String -> AbstractString)

2021-10-17 23:03 UTC, ScottPJones commented on docs/src/guide.md
> +    [`delete(r::RemoteConcept{C,T}) where {C <:AbstractThingType, T <: AbstractCoreTransaction}`](@ref)
My point,  is even if the typevars are used in the function - they are *not* needed in the documentation, and only make it longer and harder to read.

2021-10-17 23:03 UTC, ScottPJones commented on src/core/CoreSession.jl
>  function CoreSession(client::T,
Does this really need a where clause?

2021-10-17 23:03 UTC, ScottPJones commented on src/logic/Rule.jl
> +    label::AbstractString
These need to go back to String

2021-10-17 23:03 UTC, ScottPJones commented on test/behaviour/concept/type/thingtype/ThingTypeSteps.jl
> +    relation_name::String,
These should probably be AbstractString

2021-10-17 23:03 UTC, ScottPJones commented on test/behaviour/concept/type/thingtype/ThingTypeSteps.jl
> +function _get_players_contain(relation_name::String, role_name::String, context; should_contain::Bool = true)
AbstractString here?

2021-10-17 23:03 UTC, ScottPJones commented on test/behaviour/connection/transaction/TransactionSteps.jl
> +    if write
`read_write = write ? g.Proto.Transaction_Type.WRITE : g.Proto.Transaction_Type.READ`

also - `write` is a pretty bad argument name, since it conflicts with the function name

2021-10-18 15:43 UTC, FrankUrbach commented on docs/src/guide.md
> +    [`delete_database(client::CoreClient, database_name::String)`](@ref)
Done.

2021-10-18 16:48 UTC, FrankUrbach commented on docs/src/guide.md
> +* If you are only interested in working interactivly, you can use the more simplified API. An example for this is:
Done

2021-10-19 17:18 UTC, ScottPJones requested changes
Just a few places that hadn't yet been fixed, plus doing a search and replace to get rid of the unnecessary parameter `, <:AbstractCoreTransaction` from RemoteConcept in some of the files.

2021-10-19 17:18 UTC, ScottPJones commented on docs/src/examples.md
> +Or if you like to watch a Video, showing how to work with the client in a Notebook, you can watch this recording:
Lines 5-8 still need to be removed

2021-10-19 17:18 UTC, ScottPJones commented on docs/src/guide.md
> +#= Make a query in the database
This place still has the hard to read change you made to the comments.

2021-10-19 17:18 UTC, ScottPJones commented on docs/src/guide.md
> +    [`get_instances(r::RemoteConcept{<:AbstractThingType, <:AbstractCoreTransaction})`](@ref)
Tom said that the second parameter (i.e. `, <:AbstractCoreTransaction`) can be removed (so remove from both documentation and code.

2021-10-19 17:18 UTC, ScottPJones commented on docs/src/guide.md
> +    [`get_plays(r::RemoteConcept{C,T}) where
This still needs to be updated.

2021-10-19 17:18 UTC, ScottPJones commented on docs/src/guide.md
> +    [`get_regex(r::RemoteConcept{C,T}) where {
Same here.

2021-10-19 17:18 UTC, ScottPJones commented on docs/src/guide.md
> +    [`get_subtypes(r::RemoteConcept{<:AbstractType, <:AbstractCoreTransaction})`](@ref)
Make sure to remove all of the `, <:AbstractCoreTransaction` bits (should be a simple search and replace), here and in all the other places.

2021-10-19 17:18 UTC, ScottPJones commented on src/common/exception/TypeDBClientException.jl
> +function TypeDBClientException(message::AbstractString, cause::T) where {T<:Exception}
just `cause::Exception`, no need for `where` clause.

2021-10-19 17:18 UTC, ScottPJones commented on src/concept/type/AttributeType.jl
> +    get_owners(r::RemoteConcept{<: AbstractAttributeType, <:AbstractCoreTransaction}, only_key = false)
Same thing here - can remove the `, <:AbstractCoreTransaction`

2021-10-19 17:18 UTC, ScottPJones commented on src/concept/type/AttributeType.jl
> +    get_regex(r::RemoteConcept{C,T}) where {
This one can still have the C / T removed, just have `RemoteConcept{<:AbstractAttributeType}`

2021-10-19 17:18 UTC, ScottPJones commented on src/concept/type/AttributeType.jl
> +to proof the incoming string to fulfill the pattern. Otherwise the insert will fail.
"to check that the incoming string matches the pattern, otherwise the insert will fail."

2021-10-19 17:18 UTC, ScottPJones commented on src/concept/type/AttributeType.jl
> +The function wil set a regex string to a given attribute. The regex string follows the
spelling (wil -> will)

2021-10-19 17:18 UTC, ScottPJones commented on src/concept/type/AttributeType.jl
> +conventionsmof the Java programming language.
"conventions of"

2021-10-19 17:18 UTC, ScottPJones commented on src/concept/type/RelationType.jl
>                      overridden_label::Optional{String} = nothing)
`Optional{<:AbstractString}`

2021-10-19 17:18 UTC, ScottPJones commented on src/concept/type/ThingType.jl
> +        return []
Is it really possible to be any type?  Or is the type of the vector something that might be more constrained?

2021-10-19 17:18 UTC, ScottPJones commented on src/contribution/contribution.jl
>                  overriden::g.Optional{String} = nothing)
Should check for `Optional{String}`, replace with `Optional{<:AbstractString}`

2021-10-19 17:18 UTC, ScottPJones commented on src/core/CoreSession.jl
>  function CoreSession(client::T,
This could just be `client::AbstractCoreClient`, like in most other places, no where clause needed

2021-10-19 17:18 UTC, ScottPJones commented on src/logic/Rule.jl
> +    label::AbstractString
This still needs to be fixed

2021-10-19 17:18 UTC, ScottPJones commented on src/standard/utils.jl
>      chunks = (s[i:i+1] for i in 1:2:length(s)-1)  # 2-char chunks
At some point - if this is used a lot, I can provide an optimized implementation of this.

2021-10-19 22:08 UTC, FrankUrbach commented on docs/src/examples.md
> +Or if you like to watch a Video, showing how to work with the client in a Notebook, you can watch this recording:
Done.

2021-10-19 22:17 UTC, FrankUrbach commented on docs/src/guide.md
> +    [`get_instances(r::RemoteConcept{<:AbstractThingType, <:AbstractCoreTransaction})`](@ref)
We have this introduced in many places. All over the tests where we used the as_remote function. This to remove isn't possible without major changes because the transaction we use here will needed to perform getting data from the database. If we want change this we should discuss this with all others.

2021-10-19 22:22 UTC, FrankUrbach commented on docs/src/guide.md
> +    [`get_instances(r::RemoteConcept{<:AbstractThingType, <:AbstractCoreTransaction})`](@ref)
A possible solution would be the usage of the transaction and the thing which is included in the remote function as separate function parameters. This feels more natural in Julia and prevent allocations where they aren't needed.

2021-10-20 05:10 UTC, ScottPJones requested changes

2021-10-20 05:10 UTC, ScottPJones commented on docs/src/examples.md
> +Or if you like to watch a Video, showing how to work with the client in a Notebook, you can watch this recording:
This still shows the duplication of lines, lines 5-8 are (less well written) duplicates of lines 9 - 12.

2021-10-20 05:10 UTC, ScottPJones commented on docs/src/guide.md
> +#= Make a query in the database
Still here

2021-10-20 05:10 UTC, ScottPJones commented on docs/src/guide.md
> +    [`get_instances(r::RemoteConcept{<:AbstractThingType, <:AbstractCoreTransaction})`](@ref)
I think you are not understanding something here.
Both Tom and I agreed that having that as part of the specification is *not* necessary.
He had said that only the first parameter is needed for dispatching.

2021-10-20 05:10 UTC, ScottPJones commented on docs/src/guide.md
> +    [`get_rule(log_mgr::AbstractLogicManager, label::String)`](@ref)
This should be AbstractString

2021-10-20 10:01 UTC, FrankUrbach commented on src/common/exception/TypeDBClientException.jl
> +function TypeDBClientException(message::AbstractString, cause::T) where {T<:Exception}
Done.

2021-10-20 10:04 UTC, FrankUrbach commented on docs/src/examples.md
> +Or if you like to watch a Video, showing how to work with the client in a Notebook, you can watch this recording:
I think this isn't the case. One links target is the video on Youtube. The other link shows to the discord channel.

2021-10-20 10:06 UTC, FrankUrbach commented on docs/src/guide.md
> +#= Make a query in the database
Better?

2021-10-20 10:11 UTC, FrankUrbach commented on src/concept/type/AttributeType.jl
> +to proof the incoming string to fulfill the pattern. Otherwise the insert will fail.
Done.

2021-10-20 10:14 UTC, FrankUrbach commented on src/concept/type/ThingType.jl
> +        return []
Look at the function instantiate. There you will find all possible Types they could have. We could build a Union Type to narrow down the possible types. But I don't know if this helps to improve the type stability.

2021-10-20 10:25 UTC, FrankUrbach commented on src/concept/type/AttributeType.jl
> +    get_regex(r::RemoteConcept{C,T}) where {
Done

2021-10-20 10:32 UTC, FrankUrbach commented on src/concept/type/AttributeType.jl
> +    get_owners(r::RemoteConcept{<: AbstractAttributeType, <:AbstractCoreTransaction}, only_key = false)
Done.

2021-10-20 10:32 UTC, FrankUrbach commented on src/concept/type/AttributeType.jl
> +The function wil set a regex string to a given attribute. The regex string follows the
Done.

2021-10-20 10:33 UTC, FrankUrbach commented on src/concept/type/AttributeType.jl
> +conventionsmof the Java programming language.
Done

2021-10-20 14:53 UTC, FrankUrbach commented on src/concept/type/RelationType.jl
>                      overridden_label::Optional{String} = nothing)
Done.

2021-10-20 14:55 UTC, FrankUrbach commented on src/contribution/contribution.jl
>                  overriden::g.Optional{String} = nothing)
Done.

2021-10-20 14:56 UTC, FrankUrbach commented on src/core/CoreSession.jl
>  function CoreSession(client::T,
Done.

2021-10-20 14:58 UTC, FrankUrbach commented on src/logic/Rule.jl
> +    label::AbstractString
Done.

2021-10-20 15:00 UTC, FrankUrbach commented on src/standard/utils.jl
>      chunks = (s[i:i+1] for i in 1:2:length(s)-1)  # 2-char chunks
Ok.

2021-10-20 16:26 UTC, ScottPJones requested changes

2021-10-20 16:26 UTC, ScottPJones commented on docs/src/guide.md
> +    [`get_rule(log_mgr::AbstractLogicManager, label::String)`](@ref)
Still needs a change

2021-10-20 16:26 UTC, ScottPJones commented on src/concept/type/AttributeType.jl
> +conventionsmof the Java programming language.
still there (conventionsmof -> conventions of)

2021-10-20 16:26 UTC, ScottPJones commented on src/concept/type/RelationType.jl
>                      overridden_label::Optional{String} = nothing)
Actually, that wasn't the change requested - line 15 should be AbstractString, and line 16 should be Optional{AbstractString}

2021-10-20 16:26 UTC, ScottPJones commented on src/concept/type/ThingType.jl
> +        return []
If the union is small, Julia can generate much more efficient code

2021-10-20 17:11 UTC, FrankUrbach commented on src/concept/type/AttributeType.jl
> +conventionsmof the Java programming language.
Done

2021-10-20 17:14 UTC, FrankUrbach commented on src/concept/type/RelationType.jl
>                      overridden_label::Optional{String} = nothing)
Done.

2021-10-20 17:24 UTC, FrankUrbach commented on src/concept/type/ThingType.jl
> +        return []
Because not all Types are definiend until we reach this only the AbstractTypes are available. If this helps, we can use this as made above.

2021-10-20 17:26 UTC, FrankUrbach commented on docs/src/guide.md
> +    [`get_rule(log_mgr::AbstractLogicManager, label::String)`](@ref)
Done

2021-10-20 18:16 UTC, ScottPJones approved these changes

2021-10-20 18:30 UTC, merged